            - name: Prevasio Container Security
  # You may pin to the exact commit or the version.
  # uses: algosec/prevasio-cicd-container-security-action@7e1676e311785a9e0062f8ad066960a231820106
  uses: algosec/prevasio-cicd-container-security-action@v1.0.4
          
